sudo: required
services:
  - docker

before_install:
  - docker build -t saadia45/complex-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run saadia45/complex-react-test npm test -- --coverage
  - OR you should update to latest script
  - docker run -e CI=true saadia45/complex-react-test npm test

after_success:
  - docker build -t saadia45/multi-client ./client
  - docker build -t saadia45/multi-nginx ./nginx
  - docker build -t saadia45/multi-server ./server
  - docker build -t saadia45/multi-worker ./worker

